In [ ]:
#data preparation

In [1]:
#import standard stats table for the Top5 European 
#football for 2024/25 season
import pandas as pd
import numpy as np
dataset_standard = pd.read_csv("fbref_big5_stats_24_25_standard.csv")
print(dataset_standard)

        Rk             Player   Nation    Pos        Squad  \
0        1         Max Aarons  eng ENG     DF  Bournemouth
1        2         Max Aarons  eng ENG  DF,MF     Valencia
2        3     Rodrigo Abajas   es ESP     DF     Valencia
3        4     James Abankwah   ie IRL  DF,MF      Udinese
4        5  Keyliane Abdallah   fr FRA     FW    Marseille
...    ...                ...      ...    ...          ...
2849  2850       Edhy Zuliani   fr FRA     DF     Toulouse
2850  2851   Szymon Żurkowski   pl POL     MF       Empoli
2851  2852    Martin Ødegaard   no NOR     MF      Arsenal
2852  2853        Milan Đurić   ba BIH     FW        Monza
2853  2854        Milan Đurić   ba BIH     FW        Parma

                    Comp   Age    Born  MP  Starts  ...  Gls.1  Ast.1  G+A.1  \
0     eng Premier League  24.0  2000.0   3       1  ...   0.00   0.00   0.00
1             es La Liga  24.0  2000.0   4       1  ...   0.00   0.00   0.00
2             es La Liga  21.0  2003.0   1       1  ...   0.00   0.00   0.00
3             it Serie A  20.0  2004.0   6       0  ...   0.00   0.00   0.00
4             fr Ligue 1  18.0  2006.0   1       0  ...   0.00   0.00   0.00
...                  ...   ...     ...  ..     ...  ...    ...    ...    ...
2849          fr Ligue 1  19.0  2004.0   1       0  ...   0.00   0.00   0.00
2850          it Serie A  26.0  1997.0   5       0  ...   0.00   0.00   0.00
2851  eng Premier League  25.0  1998.0  30      26  ...   0.12   0.31   0.43
2852          it Serie A  34.0  1990.0  18      13  ...   0.28   0.07   0.35
2853          it Serie A  34.0  1990.0   9       3  ...   0.34   0.00   0.34

      G-PK.1  G+A-PK  xG.1  xAG.1  xG+xAG  npxG.1  npxG+xAG.1
0       0.00    0.00  0.00   0.00    0.00    0.00        0.00
1       0.00    0.00  0.00   0.02    0.02    0.00        0.02
2       0.00    0.00  0.10   0.00    0.10    0.10        0.10
3       0.00    0.00  0.06   0.00    0.06    0.06        0.06
4       0.00    0.00  0.00   0.00    0.00    0.00        0.00
...      ...     ...   ...    ...     ...     ...         ...
2849    0.00    0.00  0.00   0.00    0.00    0.00        0.00
2850    0.00    0.00  0.07   0.00    0.07    0.07        0.07
2851    0.08    0.39  0.19   0.21    0.40    0.16        0.37
2852    0.28    0.35  0.21   0.08    0.28    0.21        0.28
2853    0.34    0.34  0.08   0.00    0.08    0.08        0.08

[2854 rows x 37 columns]

In [3]:
#rename columns in standard stats table to easy to undertand words using Fbref glossary 
rename_columns = {
    "Rk": "Rank",
    "Nation": "Nationality",
    "Pos": "Position",
    "Comp": "Competition",
    "Age": "Age",
    "Born": "Birth_Year",
    
    #playing time
    "MP": "Matches_Played",
    "Starts": "Games_Started",
    "Min": "Minutes",
    "90s": "90s_Played",
    
    #performance
    "Gls": "Goals",
    "Ast": "Assists",
    "G+A": "Goals_Plus_Assists",
    "G-PK": "Non_Penalty_Goals",
    "PK": "Penalties_Made",
    "PKatt": "Penalties_Attempted",
    "CrdY": "Yellow_Cards",
    "CrdR": "Red_Cards",
    
    #expected metrics
    "xG": "Expected_Goals",
    "npxG": "Non_Penalty_xG",
    "xAG": "Exp_Assisted_Goals",
    "npxG+xAG": "Non_Penalty_xG_Plus_xAG",
    
    #progression
    "PrgC": "Progressive_Carries",
    "PrgP": "Progressive_Passes",
    "PrgR": "Progressive_Passes_Received",

    #stats PER 90
    "Gls.1": "Goals_Per_90",
    "Ast.1": "Assists_Per_90",
    "G+A.1": "Goals_Plus_Assists_Per_90",
    "G-PK.1": "Non_Penalty_Goals_Per_90",
    "G+A-PK": "Non_Penalty_Goals_Plus_Assists_Per_90",
    "xG.1": "Expected_Goals_Per_90",
    "xAG.1": "Exp_Assisted_Goals_Per_90",
    "xG+xAG": "Exp_Goals_Plus_Exp_Assists_Per_90",     
    "npxG.1": "Non_Penalty_xG_Per_90",
    "npxG+xAG.1": "Non_Penalty_xG_Plus_Exp_Assists_Per_90",

}
dataset_standard = dataset_standard.rename(columns=rename_columns)

print(dataset_standard)

      Rank             Player Nationality Position        Squad  \
0        1         Max Aarons     eng ENG       DF  Bournemouth
1        2         Max Aarons     eng ENG    DF,MF     Valencia
2        3     Rodrigo Abajas      es ESP       DF     Valencia
3        4     James Abankwah      ie IRL    DF,MF      Udinese
4        5  Keyliane Abdallah      fr FRA       FW    Marseille
...    ...                ...         ...      ...          ...
2849  2850       Edhy Zuliani      fr FRA       DF     Toulouse
2850  2851   Szymon Żurkowski      pl POL       MF       Empoli
2851  2852    Martin Ødegaard      no NOR       MF      Arsenal
2852  2853        Milan Đurić      ba BIH       FW        Monza
2853  2854        Milan Đurić      ba BIH       FW        Parma

             Competition   Age  Birth_Year  Matches_Played  Games_Started  \
0     eng Premier League  24.0      2000.0               3              1
1             es La Liga  24.0      2000.0               4              1
2             es La Liga  21.0      2003.0               1              1
3             it Serie A  20.0      2004.0               6              0
4             fr Ligue 1  18.0      2006.0               1              0
...                  ...   ...         ...             ...            ...
2849          fr Ligue 1  19.0      2004.0               1              0
2850          it Serie A  26.0      1997.0               5              0
2851  eng Premier League  25.0      1998.0              30             26
2852          it Serie A  34.0      1990.0              18             13
2853          it Serie A  34.0      1990.0               9              3

      ...  Goals_Per_90  Assists_Per_90  Goals_Plus_Assists_Per_90  \
0     ...          0.00            0.00                       0.00
1     ...          0.00            0.00                       0.00
2     ...          0.00            0.00                       0.00
3     ...          0.00            0.00                       0.00
4     ...          0.00            0.00                       0.00
...   ...           ...             ...                        ...
2849  ...          0.00            0.00                       0.00
2850  ...          0.00            0.00                       0.00
2851  ...          0.12            0.31                       0.43
2852  ...          0.28            0.07                       0.35
2853  ...          0.34            0.00                       0.34

      Non_Penalty_Goals_Per_90  Non_Penalty_Goals_Plus_Assists_Per_90  \
0                         0.00                                   0.00
1                         0.00                                   0.00
2                         0.00                                   0.00
3                         0.00                                   0.00
4                         0.00                                   0.00
...                        ...                                    ...
2849                      0.00                                   0.00
2850                      0.00                                   0.00
2851                      0.08                                   0.39
2852                      0.28                                   0.35
2853                      0.34                                   0.34

      Expected_Goals_Per_90  Exp_Assisted_Goals_Per_90  \
0                      0.00                       0.00
1                      0.00                       0.02
2                      0.10                       0.00
3                      0.06                       0.00
4                      0.00                       0.00
...                     ...                        ...
2849                   0.00                       0.00
2850                   0.07                       0.00
2851                   0.19                       0.21
2852                   0.21                       0.08
2853                   0.08                       0.00

      Exp_Goals_Plus_Exp_Assists_Per_90  Non_Penalty_xG_Per_90  \
0                                  0.00                   0.00
1                                  0.02                   0.00
2                                  0.10                   0.10
3                                  0.06                   0.06
4                                  0.00                   0.00
...                                 ...                    ...
2849                               0.00                   0.00
2850                               0.07                   0.07
2851                               0.40                   0.16
2852                               0.28                   0.21
2853                               0.08                   0.08

      Non_Penalty_xG_Plus_Exp_Assists_Per_90
0                                       0.00
1                                       0.02
2                                       0.10
3                                       0.06
4                                       0.00
...                                      ...
2849                                    0.00
2850                                    0.07
2851                                    0.37
2852                                    0.28
2853                                    0.08

[2854 rows x 37 columns]

In [4]:
# feature engineering – per-90 stats 
# add missing per-90 progressive stats
dataset_standard['Progressive_Carries_Per_90'] = dataset_standard['Progressive_Carries'] / dataset_standard['90s_Played']
dataset_standard['Progressive_Passes_Per_90'] = dataset_standard['Progressive_Passes'] / dataset_standard['90s_Played']
dataset_standard['Progressive_Passes_Received_Per_90'] = dataset_standard['Progressive_Passes_Received'] / dataset_standard['90s_Played']
dataset_standard['Yellow_Cards_Per_90'] = dataset_standard['Yellow_Cards'] / dataset_standard['90s_Played']
dataset_standard['Red_Cards_Per_90'] = dataset_standard['Red_Cards'] / dataset_standard['90s_Played']
dataset_standard['Penalties_Attempted_Per_90'] = dataset_standard['Penalties_Attempted'] / dataset_standard['90s_Played']

In [5]:
print(dataset_standard)
print(dataset_standard.columns)

      Rank             Player Nationality Position        Squad  \
0        1         Max Aarons     eng ENG       DF  Bournemouth
1        2         Max Aarons     eng ENG    DF,MF     Valencia
2        3     Rodrigo Abajas      es ESP       DF     Valencia
3        4     James Abankwah      ie IRL    DF,MF      Udinese
4        5  Keyliane Abdallah      fr FRA       FW    Marseille
...    ...                ...         ...      ...          ...
2849  2850       Edhy Zuliani      fr FRA       DF     Toulouse
2850  2851   Szymon Żurkowski      pl POL       MF       Empoli
2851  2852    Martin Ødegaard      no NOR       MF      Arsenal
2852  2853        Milan Đurić      ba BIH       FW        Monza
2853  2854        Milan Đurić      ba BIH       FW        Parma

             Competition   Age  Birth_Year  Matches_Played  Games_Started  \
0     eng Premier League  24.0      2000.0               3              1
1             es La Liga  24.0      2000.0               4              1
2             es La Liga  21.0      2003.0               1              1
3             it Serie A  20.0      2004.0               6              0
4             fr Ligue 1  18.0      2006.0               1              0
...                  ...   ...         ...             ...            ...
2849          fr Ligue 1  19.0      2004.0               1              0
2850          it Serie A  26.0      1997.0               5              0
2851  eng Premier League  25.0      1998.0              30             26
2852          it Serie A  34.0      1990.0              18             13
2853          it Serie A  34.0      1990.0               9              3

      ...  Exp_Assisted_Goals_Per_90  Exp_Goals_Plus_Exp_Assists_Per_90  \
0     ...                       0.00                               0.00
1     ...                       0.02                               0.02
2     ...                       0.00                               0.10
3     ...                       0.00                               0.06
4     ...                       0.00                               0.00
...   ...                        ...                                ...
2849  ...                       0.00                               0.00
2850  ...                       0.00                               0.07
2851  ...                       0.21                               0.40
2852  ...                       0.08                               0.28
2853  ...                       0.00                               0.08

      Non_Penalty_xG_Per_90  Non_Penalty_xG_Plus_Exp_Assists_Per_90  \
0                      0.00                                    0.00
1                      0.00                                    0.02
2                      0.10                                    0.10
3                      0.06                                    0.06
4                      0.00                                    0.00
...                     ...                                     ...
2849                   0.00                                    0.00
2850                   0.07                                    0.07
2851                   0.16                                    0.37
2852                   0.21                                    0.28
2853                   0.08                                    0.08

      Progressive_Carries_Per_90  Progressive_Passes_Per_90  \
0                       1.000000                   8.000000
1                       0.000000                   4.615385
2                       4.285714                   2.857143
3                       3.000000                   4.000000
4                            inf                        NaN
...                          ...                        ...
2849                    0.000000                   0.000000
2850                    0.833333                   0.833333
2851                    3.565891                  10.000000
2852                    0.141844                   1.489362
2853                    0.000000                   2.333333

      Progressive_Passes_Received_Per_90  Yellow_Cards_Per_90  \
0                               3.000000             0.000000
1                               7.692308             1.538462
2                               4.285714             1.428571
3                               1.000000             1.000000
4                                    NaN                  NaN
...                                  ...                  ...
2849                            0.000000             0.000000
2850                            2.500000             0.000000
2851                            5.968992             0.155039
2852                            2.127660             0.212766
2853                            2.000000             0.333333

      Red_Cards_Per_90  Penalties_Attempted_Per_90
0                  0.0                     0.00000
1                  0.0                     0.00000
2                  0.0                     0.00000
3                  0.0                     0.00000
4                  NaN                         NaN
...                ...                         ...
2849               0.0                     0.00000
2850               0.0                     0.00000
2851               0.0                     0.03876
2852               0.0                     0.00000
2853               0.0                     0.00000

[2854 rows x 43 columns]
Index(['Rank', 'Player', 'Nationality', 'Position', 'Squad', 'Competition',
       'Age', 'Birth_Year', 'Matches_Played', 'Games_Started', 'Minutes',
       '90s_Played', 'Goals', 'Assists', 'Goals_Plus_Assists',
       'Non_Penalty_Goals', 'Penalties_Made', 'Penalties_Attempted',
       'Yellow_Cards', 'Red_Cards', 'Expected_Goals', 'Non_Penalty_xG',
       'Exp_Assisted_Goals', 'Non_Penalty_xG_Plus_xAG', 'Progressive_Carries',
       'Progressive_Passes', 'Progressive_Passes_Received', 'Goals_Per_90',
       'Assists_Per_90', 'Goals_Plus_Assists_Per_90',
       'Non_Penalty_Goals_Per_90', 'Non_Penalty_Goals_Plus_Assists_Per_90',
       'Expected_Goals_Per_90', 'Exp_Assisted_Goals_Per_90',
       'Exp_Goals_Plus_Exp_Assists_Per_90', 'Non_Penalty_xG_Per_90',
       'Non_Penalty_xG_Plus_Exp_Assists_Per_90', 'Progressive_Carries_Per_90',
       'Progressive_Passes_Per_90', 'Progressive_Passes_Received_Per_90',
       'Yellow_Cards_Per_90', 'Red_Cards_Per_90',
       'Penalties_Attempted_Per_90'],
      dtype='object')

In [10]:
#keep only per90 columns

#columns to merge with
cols_to_merge = ['Rank', 'Player', 'Nationality', 'Position', 'Age', 
           'Birth_Year', 'Matches_Played', 'Games_Started', 'Minutes','90s_Played']
#per_90 columns
per90_cols = [col for col in dataset_standard.columns if col.endswith('_90')]
#new dataset
dataset_standard_1 = dataset_standard[cols_to_merge + per90_cols]

print(dataset_standard_1)
print(dataset_standard_1.columns)

      Rank             Player Nationality Position   Age  Birth_Year  \
0        1         Max Aarons     eng ENG       DF  24.0      2000.0
1        2         Max Aarons     eng ENG    DF,MF  24.0      2000.0
2        3     Rodrigo Abajas      es ESP       DF  21.0      2003.0
3        4     James Abankwah      ie IRL    DF,MF  20.0      2004.0
4        5  Keyliane Abdallah      fr FRA       FW  18.0      2006.0
...    ...                ...         ...      ...   ...         ...
2849  2850       Edhy Zuliani      fr FRA       DF  19.0      2004.0
2850  2851   Szymon Żurkowski      pl POL       MF  26.0      1997.0
2851  2852    Martin Ødegaard      no NOR       MF  25.0      1998.0
2852  2853        Milan Đurić      ba BIH       FW  34.0      1990.0
2853  2854        Milan Đurić      ba BIH       FW  34.0      1990.0

      Matches_Played  Games_Started  Minutes  90s_Played  ...  \
0                  3              1       86         1.0  ...
1                  4              1      120         1.3  ...
2                  1              1       65         0.7  ...
3                  6              0       88         1.0  ...
4                  1              0        3         0.0  ...
...              ...            ...      ...         ...  ...
2849               1              0        9         0.1  ...
2850               5              0      106         1.2  ...
2851              30             26     2325        25.8  ...
2852              18             13     1270        14.1  ...
2853               9              3      268         3.0  ...

      Exp_Assisted_Goals_Per_90  Exp_Goals_Plus_Exp_Assists_Per_90  \
0                          0.00                               0.00
1                          0.02                               0.02
2                          0.00                               0.10
3                          0.00                               0.06
4                          0.00                               0.00
...                         ...                                ...
2849                       0.00                               0.00
2850                       0.00                               0.07
2851                       0.21                               0.40
2852                       0.08                               0.28
2853                       0.00                               0.08

      Non_Penalty_xG_Per_90  Non_Penalty_xG_Plus_Exp_Assists_Per_90  \
0                      0.00                                    0.00
1                      0.00                                    0.02
2                      0.10                                    0.10
3                      0.06                                    0.06
4                      0.00                                    0.00
...                     ...                                     ...
2849                   0.00                                    0.00
2850                   0.07                                    0.07
2851                   0.16                                    0.37
2852                   0.21                                    0.28
2853                   0.08                                    0.08

      Progressive_Carries_Per_90  Progressive_Passes_Per_90  \
0                       1.000000                   8.000000
1                       0.000000                   4.615385
2                       4.285714                   2.857143
3                       3.000000                   4.000000
4                            inf                        NaN
...                          ...                        ...
2849                    0.000000                   0.000000
2850                    0.833333                   0.833333
2851                    3.565891                  10.000000
2852                    0.141844                   1.489362
2853                    0.000000                   2.333333

      Progressive_Passes_Received_Per_90  Yellow_Cards_Per_90  \
0                               3.000000             0.000000
1                               7.692308             1.538462
2                               4.285714             1.428571
3                               1.000000             1.000000
4                                    NaN                  NaN
...                                  ...                  ...
2849                            0.000000             0.000000
2850                            2.500000             0.000000
2851                            5.968992             0.155039
2852                            2.127660             0.212766
2853                            2.000000             0.333333

      Red_Cards_Per_90  Penalties_Attempted_Per_90
0                  0.0                     0.00000
1                  0.0                     0.00000
2                  0.0                     0.00000
3                  0.0                     0.00000
4                  NaN                         NaN
...                ...                         ...
2849               0.0                     0.00000
2850               0.0                     0.00000
2851               0.0                     0.03876
2852               0.0                     0.00000
2853               0.0                     0.00000

[2854 rows x 26 columns]
Index(['Rank', 'Player', 'Nationality', 'Position', 'Age', 'Birth_Year',
       'Matches_Played', 'Games_Started', 'Minutes', '90s_Played',
       'Goals_Per_90', 'Assists_Per_90', 'Goals_Plus_Assists_Per_90',
       'Non_Penalty_Goals_Per_90', 'Non_Penalty_Goals_Plus_Assists_Per_90',
       'Expected_Goals_Per_90', 'Exp_Assisted_Goals_Per_90',
       'Exp_Goals_Plus_Exp_Assists_Per_90', 'Non_Penalty_xG_Per_90',
       'Non_Penalty_xG_Plus_Exp_Assists_Per_90', 'Progressive_Carries_Per_90',
       'Progressive_Passes_Per_90', 'Progressive_Passes_Received_Per_90',
       'Yellow_Cards_Per_90', 'Red_Cards_Per_90',
       'Penalties_Attempted_Per_90'],
      dtype='object')

In [7]:
#import defense stats table for the Top5 European 
#football for 2024/25 season
dataset_defense = pd.read_csv("fbref_big5_stats_24_25_def.csv")
print(dataset_defense)

        Rk             Player   Nation    Pos        Squad  \
0        1         Max Aarons  eng ENG     DF  Bournemouth
1        2         Max Aarons  eng ENG  DF,MF     Valencia
2        3     Rodrigo Abajas   es ESP     DF     Valencia
3        4     James Abankwah   ie IRL  DF,MF      Udinese
4        5  Keyliane Abdallah   fr FRA     FW    Marseille
...    ...                ...      ...    ...          ...
2849  2850       Edhy Zuliani   fr FRA     DF     Toulouse
2850  2851   Szymon Żurkowski   pl POL     MF       Empoli
2851  2852    Martin Ødegaard   no NOR     MF      Arsenal
2852  2853        Milan Đurić   ba BIH     FW        Monza
2853  2854        Milan Đurić   ba BIH     FW        Parma

                    Comp   Age    Born   90s  Tkl  ...  Att   Tkl%  Lost  \
0     eng Premier League  24.0  2000.0   1.0    2  ...    1  100.0     0
1             es La Liga  24.0  2000.0   1.3    4  ...    5   80.0     1
2             es La Liga  21.0  2003.0   0.7    3  ...    3  100.0     0
3             it Serie A  20.0  2004.0   1.0    4  ...    3   66.7     1
4             fr Ligue 1  18.0  2006.0   0.0    1  ...    1  100.0     0
...                  ...   ...     ...   ...  ...  ...  ...    ...   ...
2849          fr Ligue 1  19.0  2004.0   0.1    0  ...    0    NaN     0
2850          it Serie A  26.0  1997.0   1.2    6  ...    4  100.0     0
2851  eng Premier League  25.0  1998.0  25.8   19  ...   25   16.0    21
2852          it Serie A  34.0  1990.0  14.1    1  ...    3    0.0     3
2853          it Serie A  34.0  1990.0   3.0    0  ...    2    0.0     2

      Blocks  Sh  Pass  Int  Tkl+Int  Clr  Err
0          3   1     2    1        3    0    0
1          1   0     1    0        4    3    0
2          1   0     1    1        4    0    0
3          2   1     1    1        5    3    0
4          0   0     0    0        1    0    0
...      ...  ..   ...  ...      ...  ...  ...
2849       0   0     0    1        1    0    0
2850       3   0     3    1        7    2    0
2851       5   0     5    6       25    6    1
2852       6   0     6    2        3   17    0
2853       3   0     3    0        0    2    0

[2854 rows x 25 columns]

In [8]:
#rename columns in defense stats table to easy to undertand words using Fbref glossary 

rename_defensive_columns = {
    "Rk": "Rank",
    "Nation": "Nationality",
    "Pos": "Position",
    "Comp": "Competition",
    "Age": "Age",
    "Born": "Birth_Year",
    "90s": "90s_Played",

    #tackles
    "Tkl": "Tackles",             
    "TklW": "Tackles_Won",          
    "Def 3rd": "Tackles_Def_3rd", 
    "Mid 3rd": "Tackles_Mid_3rd", 
    "Att 3rd": "Tackles_Att_3rd", 

    #challenges 
    "Tkl.1": "Dribblers_Tackled", 
    "Att": "Dribbles_Challenged",
    "Tkl%": "%_Dribblers_Tackled",
    "Lost": "Challenges_Lost",      

    #blocks
    "Blocks": "Blocks",             
    "Sh": "Shots_Blocked",
    "Pass": "Passes_Blocked",

    # Interceptions, Clearances, Errors
    "Int": "Interceptions",
    "Tkl+Int": "Tackles_Plus_Interceptions",
    "Clr": "Clearances",
    "Err": "Errors_Leading_To_Shot"
}

dataset_defense = dataset_defense.rename(columns=rename_defensive_columns)

print(dataset_defense)

      Rank             Player Nationality Position        Squad  \
0        1         Max Aarons     eng ENG       DF  Bournemouth
1        2         Max Aarons     eng ENG    DF,MF     Valencia
2        3     Rodrigo Abajas      es ESP       DF     Valencia
3        4     James Abankwah      ie IRL    DF,MF      Udinese
4        5  Keyliane Abdallah      fr FRA       FW    Marseille
...    ...                ...         ...      ...          ...
2849  2850       Edhy Zuliani      fr FRA       DF     Toulouse
2850  2851   Szymon Żurkowski      pl POL       MF       Empoli
2851  2852    Martin Ødegaard      no NOR       MF      Arsenal
2852  2853        Milan Đurić      ba BIH       FW        Monza
2853  2854        Milan Đurić      ba BIH       FW        Parma

             Competition   Age  Birth_Year  90s_Played  Tackles  ...  \
0     eng Premier League  24.0      2000.0         1.0        2  ...
1             es La Liga  24.0      2000.0         1.3        4  ...
2             es La Liga  21.0      2003.0         0.7        3  ...
3             it Serie A  20.0      2004.0         1.0        4  ...
4             fr Ligue 1  18.0      2006.0         0.0        1  ...
...                  ...   ...         ...         ...      ...  ...
2849          fr Ligue 1  19.0      2004.0         0.1        0  ...
2850          it Serie A  26.0      1997.0         1.2        6  ...
2851  eng Premier League  25.0      1998.0        25.8       19  ...
2852          it Serie A  34.0      1990.0        14.1        1  ...
2853          it Serie A  34.0      1990.0         3.0        0  ...

      Dribbles_Challenged  %_Dribblers_Tackled  Challenges_Lost  Blocks  \
0                       1                100.0                0       3
1                       5                 80.0                1       1
2                       3                100.0                0       1
3                       3                 66.7                1       2
4                       1                100.0                0       0
...                   ...                  ...              ...     ...
2849                    0                  NaN                0       0
2850                    4                100.0                0       3
2851                   25                 16.0               21       5
2852                    3                  0.0                3       6
2853                    2                  0.0                2       3

      Shots_Blocked  Passes_Blocked  Interceptions  \
0                 1               2              1
1                 0               1              0
2                 0               1              1
3                 1               1              1
4                 0               0              0
...             ...             ...            ...
2849              0               0              1
2850              0               3              1
2851              0               5              6
2852              0               6              2
2853              0               3              0

      Tackles_Plus_Interceptions  Clearances  Errors_Leading_To_Shot
0                              3           0                       0
1                              4           3                       0
2                              4           0                       0
3                              5           3                       0
4                              1           0                       0
...                          ...         ...                     ...
2849                           1           0                       0
2850                           7           2                       0
2851                          25           6                       1
2852                           3          17                       0
2853                           0           2                       0

[2854 rows x 25 columns]

In [9]:
#convert columns in the defense dataset to per90 
defensive_stats_per90 = [
    'Tackles',
    'Tackles_Won',
    'Tackles_Def_3rd',
    'Tackles_Mid_3rd',
    'Tackles_Att_3rd',
    'Dribblers_Tackled',
    'Dribbles_Challenged',
    'Challenges_Lost',
    'Blocks',
    'Shots_Blocked',
    'Passes_Blocked',
    'Interceptions',
    'Tackles_Plus_Interceptions',
    'Clearances',
    'Errors_Leading_To_Shot'
]

for col in defensive_stats_per90:
    new_col_name = f"{col}_Per_90"
    dataset_defense[new_col_name] = dataset_defense[col] / dataset_defense['90s_Played']
    
print(dataset_defense)
print(dataset_defense.columns)

      Rank             Player Nationality Position        Squad  \
0        1         Max Aarons     eng ENG       DF  Bournemouth
1        2         Max Aarons     eng ENG    DF,MF     Valencia
2        3     Rodrigo Abajas      es ESP       DF     Valencia
3        4     James Abankwah      ie IRL    DF,MF      Udinese
4        5  Keyliane Abdallah      fr FRA       FW    Marseille
...    ...                ...         ...      ...          ...
2849  2850       Edhy Zuliani      fr FRA       DF     Toulouse
2850  2851   Szymon Żurkowski      pl POL       MF       Empoli
2851  2852    Martin Ødegaard      no NOR       MF      Arsenal
2852  2853        Milan Đurić      ba BIH       FW        Monza
2853  2854        Milan Đurić      ba BIH       FW        Parma

             Competition   Age  Birth_Year  90s_Played  Tackles  ...  \
0     eng Premier League  24.0      2000.0         1.0        2  ...
1             es La Liga  24.0      2000.0         1.3        4  ...
2             es La Liga  21.0      2003.0         0.7        3  ...
3             it Serie A  20.0      2004.0         1.0        4  ...
4             fr Ligue 1  18.0      2006.0         0.0        1  ...
...                  ...   ...         ...         ...      ...  ...
2849          fr Ligue 1  19.0      2004.0         0.1        0  ...
2850          it Serie A  26.0      1997.0         1.2        6  ...
2851  eng Premier League  25.0      1998.0        25.8       19  ...
2852          it Serie A  34.0      1990.0        14.1        1  ...
2853          it Serie A  34.0      1990.0         3.0        0  ...

      Dribblers_Tackled_Per_90  Dribbles_Challenged_Per_90  \
0                     1.000000                    1.000000
1                     3.076923                    3.846154
2                     4.285714                    4.285714
3                     2.000000                    3.000000
4                          inf                         inf
...                        ...                         ...
2849                  0.000000                    0.000000
2850                  3.333333                    3.333333
2851                  0.155039                    0.968992
2852                  0.000000                    0.212766
2853                  0.000000                    0.666667

      Challenges_Lost_Per_90  Blocks_Per_90  Shots_Blocked_Per_90  \
0                   0.000000       3.000000                   1.0
1                   0.769231       0.769231                   0.0
2                   0.000000       1.428571                   0.0
3                   1.000000       2.000000                   1.0
4                        NaN            NaN                   NaN
...                      ...            ...                   ...
2849                0.000000       0.000000                   0.0
2850                0.000000       2.500000                   0.0
2851                0.813953       0.193798                   0.0
2852                0.212766       0.425532                   0.0
2853                0.666667       1.000000                   0.0

      Passes_Blocked_Per_90  Interceptions_Per_90  \
0                  2.000000              1.000000
1                  0.769231              0.000000
2                  1.428571              1.428571
3                  1.000000              1.000000
4                       NaN                   NaN
...                     ...                   ...
2849               0.000000             10.000000
2850               2.500000              0.833333
2851               0.193798              0.232558
2852               0.425532              0.141844
2853               1.000000              0.000000

      Tackles_Plus_Interceptions_Per_90  Clearances_Per_90  \
0                              3.000000           0.000000
1                              3.076923           2.307692
2                              5.714286           0.000000
3                              5.000000           3.000000
4                                   inf                NaN
...                                 ...                ...
2849                          10.000000           0.000000
2850                           5.833333           1.666667
2851                           0.968992           0.232558
2852                           0.212766           1.205674
2853                           0.000000           0.666667

      Errors_Leading_To_Shot_Per_90
0                           0.00000
1                           0.00000
2                           0.00000
3                           0.00000
4                               NaN
...                             ...
2849                        0.00000
2850                        0.00000
2851                        0.03876
2852                        0.00000
2853                        0.00000

[2854 rows x 40 columns]
Index(['Rank', 'Player', 'Nationality', 'Position', 'Squad', 'Competition',
       'Age', 'Birth_Year', '90s_Played', 'Tackles', 'Tackles_Won',
       'Tackles_Def_3rd', 'Tackles_Mid_3rd', 'Tackles_Att_3rd',
       'Dribblers_Tackled', 'Dribbles_Challenged', '%_Dribblers_Tackled',
       'Challenges_Lost', 'Blocks', 'Shots_Blocked', 'Passes_Blocked',
       'Interceptions', 'Tackles_Plus_Interceptions', 'Clearances',
       'Errors_Leading_To_Shot', 'Tackles_Per_90', 'Tackles_Won_Per_90',
       'Tackles_Def_3rd_Per_90', 'Tackles_Mid_3rd_Per_90',
       'Tackles_Att_3rd_Per_90', 'Dribblers_Tackled_Per_90',
       'Dribbles_Challenged_Per_90', 'Challenges_Lost_Per_90', 'Blocks_Per_90',
       'Shots_Blocked_Per_90', 'Passes_Blocked_Per_90', 'Interceptions_Per_90',
       'Tackles_Plus_Interceptions_Per_90', 'Clearances_Per_90',
       'Errors_Leading_To_Shot_Per_90'],
      dtype='object')

In [11]:
#keep only per90 columns

#columns to merge with
defs_cols_to_merge = ['Rank', 'Player', 'Nationality', 'Position', 'Age', 
           'Birth_Year','90s_Played']
#per_90 columns
per90_cols = [col for col in dataset_defense.columns if col.endswith('_90')]
#new dataset
dataset_defense_1 = dataset_defense[defs_cols_to_merge + per90_cols]

print(dataset_defense_1)
print(dataset_defense_1.columns)

      Rank             Player Nationality Position   Age  Birth_Year  \
0        1         Max Aarons     eng ENG       DF  24.0      2000.0
1        2         Max Aarons     eng ENG    DF,MF  24.0      2000.0
2        3     Rodrigo Abajas      es ESP       DF  21.0      2003.0
3        4     James Abankwah      ie IRL    DF,MF  20.0      2004.0
4        5  Keyliane Abdallah      fr FRA       FW  18.0      2006.0
...    ...                ...         ...      ...   ...         ...
2849  2850       Edhy Zuliani      fr FRA       DF  19.0      2004.0
2850  2851   Szymon Żurkowski      pl POL       MF  26.0      1997.0
2851  2852    Martin Ødegaard      no NOR       MF  25.0      1998.0
2852  2853        Milan Đurić      ba BIH       FW  34.0      1990.0
2853  2854        Milan Đurić      ba BIH       FW  34.0      1990.0

      90s_Played  Tackles_Per_90  Tackles_Won_Per_90  Tackles_Def_3rd_Per_90  \
0            1.0        2.000000            2.000000                1.000000
1            1.3        3.076923            3.076923                1.538462
2            0.7        4.285714            2.857143                2.857143
3            1.0        4.000000            2.000000                4.000000
4            0.0             inf                 inf                     inf
...          ...             ...                 ...                     ...
2849         0.1        0.000000            0.000000                0.000000
2850         1.2        5.000000            3.333333                1.666667
2851        25.8        0.736434            0.426357                0.348837
2852        14.1        0.070922            0.070922                0.000000
2853         3.0        0.000000            0.000000                0.000000

      ...  Dribblers_Tackled_Per_90  Dribbles_Challenged_Per_90  \
0     ...                  1.000000                    1.000000
1     ...                  3.076923                    3.846154
2     ...                  4.285714                    4.285714
3     ...                  2.000000                    3.000000
4     ...                       inf                         inf
...   ...                       ...                         ...
2849  ...                  0.000000                    0.000000
2850  ...                  3.333333                    3.333333
2851  ...                  0.155039                    0.968992
2852  ...                  0.000000                    0.212766
2853  ...                  0.000000                    0.666667

      Challenges_Lost_Per_90  Blocks_Per_90  Shots_Blocked_Per_90  \
0                   0.000000       3.000000                   1.0
1                   0.769231       0.769231                   0.0
2                   0.000000       1.428571                   0.0
3                   1.000000       2.000000                   1.0
4                        NaN            NaN                   NaN
...                      ...            ...                   ...
2849                0.000000       0.000000                   0.0
2850                0.000000       2.500000                   0.0
2851                0.813953       0.193798                   0.0
2852                0.212766       0.425532                   0.0
2853                0.666667       1.000000                   0.0

      Passes_Blocked_Per_90  Interceptions_Per_90  \
0                  2.000000              1.000000
1                  0.769231              0.000000
2                  1.428571              1.428571
3                  1.000000              1.000000
4                       NaN                   NaN
...                     ...                   ...
2849               0.000000             10.000000
2850               2.500000              0.833333
2851               0.193798              0.232558
2852               0.425532              0.141844
2853               1.000000              0.000000

      Tackles_Plus_Interceptions_Per_90  Clearances_Per_90  \
0                              3.000000           0.000000
1                              3.076923           2.307692
2                              5.714286           0.000000
3                              5.000000           3.000000
4                                   inf                NaN
...                                 ...                ...
2849                          10.000000           0.000000
2850                           5.833333           1.666667
2851                           0.968992           0.232558
2852                           0.212766           1.205674
2853                           0.000000           0.666667

      Errors_Leading_To_Shot_Per_90
0                           0.00000
1                           0.00000
2                           0.00000
3                           0.00000
4                               NaN
...                             ...
2849                        0.00000
2850                        0.00000
2851                        0.03876
2852                        0.00000
2853                        0.00000

[2854 rows x 22 columns]
Index(['Rank', 'Player', 'Nationality', 'Position', 'Age', 'Birth_Year',
       '90s_Played', 'Tackles_Per_90', 'Tackles_Won_Per_90',
       'Tackles_Def_3rd_Per_90', 'Tackles_Mid_3rd_Per_90',
       'Tackles_Att_3rd_Per_90', 'Dribblers_Tackled_Per_90',
       'Dribbles_Challenged_Per_90', 'Challenges_Lost_Per_90', 'Blocks_Per_90',
       'Shots_Blocked_Per_90', 'Passes_Blocked_Per_90', 'Interceptions_Per_90',
       'Tackles_Plus_Interceptions_Per_90', 'Clearances_Per_90',
       'Errors_Leading_To_Shot_Per_90'],
      dtype='object')

In [13]:
#merge both datasets and save

common_columns = ['Rank', 'Player', 'Nationality', 'Position', 'Age', 'Birth_Year', '90s_Played'
]

combined_stats_dataset = pd.merge(
    dataset_standard_1, 
    dataset_defense_1, 
    on=common_columns, 
    how='inner'
)

#save as csv file
combined_stats_dataset.to_csv('Combined_Stats_dataset.csv', index=False)

print(f"Final dataset shape: {combined_stats_dataset.shape}")
print(combined_stats_dataset)

Final dataset shape: (2854, 41)
      Rank             Player Nationality Position   Age  Birth_Year  \
0        1         Max Aarons     eng ENG       DF  24.0      2000.0
1        2         Max Aarons     eng ENG    DF,MF  24.0      2000.0
2        3     Rodrigo Abajas      es ESP       DF  21.0      2003.0
3        4     James Abankwah      ie IRL    DF,MF  20.0      2004.0
4        5  Keyliane Abdallah      fr FRA       FW  18.0      2006.0
...    ...                ...         ...      ...   ...         ...
2849  2850       Edhy Zuliani      fr FRA       DF  19.0      2004.0
2850  2851   Szymon Żurkowski      pl POL       MF  26.0      1997.0
2851  2852    Martin Ødegaard      no NOR       MF  25.0      1998.0
2852  2853        Milan Đurić      ba BIH       FW  34.0      1990.0
2853  2854        Milan Đurić      ba BIH       FW  34.0      1990.0

      Matches_Played  Games_Started  Minutes  90s_Played  ...  \
0                  3              1       86         1.0  ...
1                  4              1      120         1.3  ...
2                  1              1       65         0.7  ...
3                  6              0       88         1.0  ...
4                  1              0        3         0.0  ...
...              ...            ...      ...         ...  ...
2849               1              0        9         0.1  ...
2850               5              0      106         1.2  ...
2851              30             26     2325        25.8  ...
2852              18             13     1270        14.1  ...
2853               9              3      268         3.0  ...

      Dribblers_Tackled_Per_90  Dribbles_Challenged_Per_90  \
0                     1.000000                    1.000000
1                     3.076923                    3.846154
2                     4.285714                    4.285714
3                     2.000000                    3.000000
4                          inf                         inf
...                        ...                         ...
2849                  0.000000                    0.000000
2850                  3.333333                    3.333333
2851                  0.155039                    0.968992
2852                  0.000000                    0.212766
2853                  0.000000                    0.666667

      Challenges_Lost_Per_90  Blocks_Per_90  Shots_Blocked_Per_90  \
0                   0.000000       3.000000                   1.0
1                   0.769231       0.769231                   0.0
2                   0.000000       1.428571                   0.0
3                   1.000000       2.000000                   1.0
4                        NaN            NaN                   NaN
...                      ...            ...                   ...
2849                0.000000       0.000000                   0.0
2850                0.000000       2.500000                   0.0
2851                0.813953       0.193798                   0.0
2852                0.212766       0.425532                   0.0
2853                0.666667       1.000000                   0.0

      Passes_Blocked_Per_90  Interceptions_Per_90  \
0                  2.000000              1.000000
1                  0.769231              0.000000
2                  1.428571              1.428571
3                  1.000000              1.000000
4                       NaN                   NaN
...                     ...                   ...
2849               0.000000             10.000000
2850               2.500000              0.833333
2851               0.193798              0.232558
2852               0.425532              0.141844
2853               1.000000              0.000000

      Tackles_Plus_Interceptions_Per_90  Clearances_Per_90  \
0                              3.000000           0.000000
1                              3.076923           2.307692
2                              5.714286           0.000000
3                              5.000000           3.000000
4                                   inf                NaN
...                                 ...                ...
2849                          10.000000           0.000000
2850                           5.833333           1.666667
2851                           0.968992           0.232558
2852                           0.212766           1.205674
2853                           0.000000           0.666667

      Errors_Leading_To_Shot_Per_90
0                           0.00000
1                           0.00000
2                           0.00000
3                           0.00000
4                               NaN
...                             ...
2849                        0.00000
2850                        0.00000
2851                        0.03876
2852                        0.00000
2853                        0.00000

[2854 rows x 41 columns]

In [12]:
main_dataset.head(50)

,Rank,Player,Nationality,Position,Age,Birth_Year,Matches_Played,Games_Started,Minutes,90s_Played,...,Dribblers_Tackled_Per_90,Dribbles_Challenged_Per_90,Challenges_Lost_Per_90,Blocks_Per_90,Shots_Blocked_Per_90,Passes_Blocked_Per_90,Interceptions_Per_90,Tackles_Plus_Interceptions_Per_90,Clearances_Per_90,Errors_Leading_To_Shot_Per_90
0,1,Max Aarons,eng ENG,DF,24.0,2000.0,3,1,86,1.0,...,1.000000,1.000000,0.000000,3.000000,1.000000,2.000000,1.000000,3.000000,0.000000,0.000000
1,2,Max Aarons,eng ENG,"DF,MF",24.0,2000.0,4,1,120,1.3,...,3.076923,3.846154,0.769231,0.769231,0.000000,0.769231,0.000000,3.076923,2.307692,0.000000
2,3,Rodrigo Abajas,es ESP,DF,21.0,2003.0,1,1,65,0.7,...,4.285714,4.285714,0.000000,1.428571,0.000000,1.428571,1.428571,5.714286,0.000000,0.000000
3,4,James Abankwah,ie IRL,"DF,MF",20.0,2004.0,6,0,88,1.0,...,2.000000,3.000000,1.000000,2.000000,1.000000,1.000000,1.000000,5.000000,3.000000,0.000000
4,5,Keyliane Abdallah,fr FRA,FW,18.0,2006.0,1,0,3,0.0,...,inf,inf,NaN,NaN,NaN,NaN,NaN,inf,NaN,NaN
5,6,Yunis Abdelhamid,ma MAR,DF,36.0,1987.0,16,11,1033,11.5,...,0.869565,1.391304,0.521739,2.260870,1.565217,0.695652,1.217391,2.695652,4.956522,0.086957
6,7,Himad Abdelli,dz ALG,"MF,FW",24.0,1999.0,32,32,2842,31.6,...,0.474684,1.518987,1.044304,0.759494,0.031646,0.727848,0.822785,2.341772,0.886076,0.063291
7,8,Mohamed Abdelmoneim,eg EGY,DF,25.0,1999.0,12,10,855,9.5,...,1.368421,2.315789,0.947368,1.157895,0.526316,0.631579,1.578947,3.789474,5.894737,0.105263
8,9,Ali Abdi,tn TUN,"DF,MF",30.0,1993.0,25,17,1393,15.5,...,1.806452,2.774194,0.967742,1.290323,0.387097,0.903226,1.290323,4.064516,2.387097,0.000000
9,10,Saud Abdulhamid,sa KSA,DF,25.0,1999.0,4,2,205,2.3,...,0.434783,0.434783,0.000000,0.869565,0.000000,0.869565,0.869565,2.173913,0.000000,0.000000
10,11,Nabil Aberdin,fr FRA,MF,21.0,2002.0,7,4,263,2.9,...,0.344828,0.344828,0.000000,1.034483,0.000000,1.034483,0.000000,2.068966,1.724138,0.000000
11,12,Oliver Abildgaard,dk DEN,MF,28.0,1996.0,1,0,7,0.1,...,0.000000,0.000000,0.000000,10.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000
12,13,Matthis Abline,fr FRA,FW,21.0,2003.0,34,33,2768,30.8,...,0.097403,0.292208,0.194805,0.487013,0.032468,0.454545,0.129870,0.487013,1.168831,0.032468
13,14,Abner,br BRA,DF,24.0,2000.0,19,12,1090,12.1,...,1.735537,2.644628,0.909091,1.239669,0.165289,1.074380,0.413223,2.809917,3.388430,0.000000
14,15,Zakaria Aboukhlal,ma MAR,"MF,FW",24.0,2000.0,26,22,1901,21.1,...,0.189573,1.090047,0.900474,0.758294,0.047393,0.710900,0.284360,1.327014,0.426540,0.000000
15,16,Abdel Abqar,ma MAR,DF,25.0,1999.0,29,29,2463,27.4,...,0.729927,1.240876,0.510949,1.021898,0.656934,0.364964,1.423358,2.737226,5.328467,0.036496
16,17,Tammy Abraham,eng ENG,FW,26.0,1997.0,1,0,1,0.0,...,NaN,inf,inf,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,Tammy Abraham,eng ENG,FW,26.0,1997.0,28,12,1183,13.1,...,0.458015,0.610687,0.152672,0.992366,0.000000,0.992366,0.152672,1.450382,1.221374,0.000000
18,19,Federico Accornero,it ITA,MF,20.0,2004.0,1,0,5,0.1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,20,Francesco Acerbi,it ITA,DF,36.0,1988.0,23,20,1710,19.0,...,0.578947,0.894737,0.315789,1.157895,0.842105,0.315789,1.368421,2.578947,4.263158,0.000000
20,21,Joshua Acheampong,eng ENG,DF,18.0,2006.0,4,2,170,1.9,...,1.052632,1.052632,0.000000,0.526316,0.000000,0.526316,0.526316,1.578947,1.052632,0.000000
21,22,Akor Adams,ng NGA,FW,24.0,2000.0,4,1,134,1.5,...,0.000000,0.000000,0.000000,0.666667,0.000000,0.666667,0.000000,0.000000,0.666667,0.000000
22,23,Akor Adams,ng NGA,FW,24.0,2000.0,15,13,1075,11.9,...,0.252101,0.336134,0.084034,0.168067,0.084034,0.084034,0.084034,0.420168,0.420168,0.084034
23,24,Che Adams,sct SCO,FW,28.0,1996.0,36,30,2652,29.5,...,0.033898,0.237288,0.203390,0.440678,0.203390,0.237288,0.067797,0.474576,0.610169,0.000000
24,25,Tyler Adams,us USA,MF,25.0,1999.0,28,21,1965,21.8,...,1.788991,3.302752,1.513761,1.513761,0.458716,1.055046,1.467890,5.275229,1.926606,0.000000
25,26,Junior Adamu,at AUT,FW,23.0,2001.0,25,19,1545,17.2,...,0.174419,0.639535,0.465116,0.813953,0.000000,0.813953,0.697674,1.220930,1.162791,0.000000
26,27,Tosin Adarabioyo,eng ENG,DF,26.0,1997.0,22,15,1409,15.7,...,0.509554,0.764331,0.254777,0.573248,0.445860,0.127389,0.700637,1.783439,5.095541,0.000000
27,28,Martin Adeline,fr FRA,MF,20.0,2003.0,1,0,26,0.3,...,3.333333,6.666667,3.333333,0.000000,0.000000,0.000000,0.000000,3.333333,6.666667,0.000000
28,29,Karim Adeyemi,de GER,"FW,MF",22.0,2002.0,25,17,1433,15.9,...,0.503145,1.257862,0.754717,0.880503,0.062893,0.817610,0.440252,1.698113,0.314465,0.000000
29,30,Simon Adingra,ci CIV,"FW,MF",22.0,2002.0,29,12,1097,12.2,...,0.819672,2.131148,1.311475,0.983607,0.000000,0.983607,0.655738,2.540984,0.491803,0.163934
30,31,Amine Adli,ma MAR,"MF,FW",24.0,2000.0,20,6,766,8.5,...,0.470588,1.294118,0.823529,1.294118,0.000000,1.294118,0.000000,1.764706,0.470588,0.000000
31,32,Yacine Adli,fr FRA,MF,24.0,2000.0,26,15,1234,13.7,...,1.240876,2.846715,1.605839,0.948905,0.072993,0.875912,0.437956,2.773723,1.386861,0.000000
32,33,Adrián,es ESP,GK,37.0,1987.0,19,19,1710,19.0,...,0.000000,0.157895,0.157895,0.000000,0.000000,0.000000,0.000000,0.000000,0.736842,0.157895
33,34,Adryelson,br BRA,DF,26.0,1998.0,1,0,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,inf,inf,inf,NaN
34,35,Vasilije Adžić,me MNE,"MF,FW",18.0,2006.0,6,0,42,0.5,...,0.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000
35,36,Michel Aebischer,ch SUI,MF,27.0,1997.0,14,9,724,8.0,...,1.250000,1.750000,0.500000,0.500000,0.125000,0.375000,0.875000,3.125000,0.750000,0.000000
36,37,Oladapo Afolayan,eng ENG,"FW,MF",26.0,1998.0,32,17,1639,18.2,...,0.384615,1.043956,0.659341,0.934066,0.054945,0.879121,0.439560,1.373626,1.098901,0.000000
37,38,Emmanuel Agbadou,ci CIV,DF,27.0,1997.0,16,16,1410,15.7,...,0.828025,1.273885,0.445860,1.210191,0.828025,0.382166,0.764331,2.675159,5.732484,0.000000
38,39,Emmanuel Agbadou,ci CIV,DF,27.0,1997.0,14,14,1260,14.0,...,1.357143,1.857143,0.500000,1.571429,0.928571,0.642857,1.357143,3.142857,4.571429,0.071429
39,40,Asher Agbinone,eng ENG,MF,18.0,2005.0,2,0,6,0.1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.000000,0.000000,0.000000
40,41,Jeremy Agbonifo,se SWE,"FW,MF",18.0,2005.0,8,1,300,3.3,...,0.909091,2.121212,1.212121,0.606061,0.303030,0.303030,0.303030,2.424242,0.000000,0.303030
41,42,Julen Agirrezabala,es ESP,GK,23.0,2000.0,14,14,1206,13.4,...,0.000000,0.074627,0.074627,0.000000,0.000000,0.000000,0.000000,0.000000,0.298507,0.000000
42,43,Lucien Agoume,fr FRA,MF,22.0,2002.0,35,24,2114,23.5,...,1.148936,1.659574,0.510638,1.276596,0.468085,0.808511,1.744681,4.723404,1.787234,0.000000
43,44,Felix Agu,ng NGA,DF,24.0,1999.0,22,21,1751,19.5,...,0.615385,1.179487,0.564103,1.384615,0.461538,0.923077,1.076923,2.615385,2.461538,0.000000
44,45,Álvaro Aguado,es ESP,MF,28.0,1996.0,16,4,443,4.9,...,0.612245,1.836735,1.224490,1.428571,0.204082,1.224490,0.816327,1.836735,1.020408,0.204082
45,46,Lorenzo Aguado,es ESP,DF,21.0,2002.0,2,0,5,0.1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.000000,0.000000
46,47,Nayef Aguerd,ma MAR,DF,28.0,1996.0,21,21,1760,19.6,...,0.612245,0.918367,0.306122,1.071429,0.765306,0.306122,0.663265,2.193878,4.642857,0.000000
47,48,Ruben Aguilar,fr FRA,"DF,MF",31.0,1993.0,16,13,1124,12.5,...,1.920000,3.120000,1.200000,2.000000,0.240000,1.760000,1.040000,3.760000,1.840000,0.000000
48,49,Naouirou Ahamada,fr FRA,"MF,FW",22.0,2002.0,3,0,58,0.6,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.333333,3.333333,3.333333,0.000000
49,50,Honest Ahanor,it ITA,"DF,MF",16.0,2008.0,6,3,270,3.0,...,2.333333,3.333333,1.000000,1.333333,0.000000,1.333333,0.333333,2.666667,3.000000,0.000000

In [15]:
#keep only players with ≥450 minutes (≥5 full games)
combined_stats_dataset = combined_stats_dataset[combined_stats_dataset['Minutes'] >= 450].copy()

#remove players who appear multiple times (transfers/loans)
combined_stats_dataset = combined_stats_dataset.loc[combined_stats_dataset.groupby(['Player', 'Age'])['Minutes'].idxmax()].reset_index(drop=True)

#remove goalkeepers
combined_stats_dataset = combined_stats_dataset[combined_stats_dataset['Position'] != 'GK'].copy()

#replace nans values, if any with zero
combined_stats_dataset = combined_stats_dataset.fillna(0)
print(combined_stats_dataset)

      Rank                 Player Nationality Position   Age  Birth_Year  \
0      625        Aaron Cresswell     eng ENG       DF  34.0      1989.0
2     2744      Aaron Wan-Bissaka      cd COD       DF  26.0      1997.0
3     1638           Aarón Martín      es ESP       DF  27.0      1997.0
4     2534           Abakar Sylla      ci CIV       DF  21.0      2002.0
5     2423          Abdallah Sima      sn SEN    FW,MF  23.0      2001.0
...    ...                    ...         ...      ...   ...         ...
1939  2660         Óscar Valentín      es ESP       MF  29.0      1994.0
1940  1618        Óscar de Marcos      es ESP       DF  35.0      1989.0
1942    62             Ümit Akdag      ro ROU       DF  20.0      2003.0
1943  1265  Þórir Jóhann Helgason      is ISL       MF  23.0      2000.0
1945  1098         İlkay Gündoğan      de GER       MF  33.0      1990.0

      Matches_Played  Games_Started  Minutes  90s_Played  ...  \
0                 18             10      824         9.2  ...
2                 36             35     3154        35.0  ...
3                 36             35     3085        34.3  ...
4                 21             10      950        10.6  ...
5                 27             14     1238        13.8  ...
...              ...            ...      ...         ...  ...
1939              34             18     1835        20.4  ...
1940              26             17     1564        17.4  ...
1942               9              6      500         5.6  ...
1943              21             13     1156        12.8  ...
1945              33             25     2223        24.7  ...

      Dribblers_Tackled_Per_90  Dribbles_Challenged_Per_90  \
0                     0.978261                    1.195652
2                     0.657143                    0.914286
3                     0.962099                    1.486880
4                     1.415094                    1.603774
5                     0.289855                    0.797101
...                        ...                         ...
1939                  1.617647                    3.725490
1940                  1.206897                    2.126437
1942                  0.892857                    2.142857
1943                  0.546875                    1.015625
1945                  0.404858                    0.971660

      Challenges_Lost_Per_90  Blocks_Per_90  Shots_Blocked_Per_90  \
0                   0.217391       0.978261              0.434783
2                   0.257143       1.057143              0.314286
3                   0.524781       0.962099              0.320700
4                   0.188679       1.698113              0.943396
5                   0.507246       0.652174              0.072464
...                      ...            ...                   ...
1939                2.107843       1.764706              0.392157
1940                0.919540       0.977011              0.057471
1942                1.250000       1.785714              1.428571
1943                0.468750       0.546875              0.156250
1945                0.566802       0.607287              0.000000

      Passes_Blocked_Per_90  Interceptions_Per_90  \
0                  0.543478              0.869565
2                  0.742857              1.885714
3                  0.641399              0.553936
4                  0.754717              1.037736
5                  0.579710              0.072464
...                     ...                   ...
1939               1.372549              1.029412
1940               0.919540              0.919540
1942               0.357143              1.964286
1943               0.390625              0.468750
1945               0.607287              0.526316

      Tackles_Plus_Interceptions_Per_90  Clearances_Per_90  \
0                              2.065217           4.021739
2                              3.885714           3.571429
3                              2.623907           2.128280
4                              3.584906           5.943396
5                              1.159420           0.652174
...                                 ...                ...
1939                           3.725490           2.500000
1940                           2.758621           2.011494
1942                           3.392857           3.392857
1943                           1.250000           0.859375
1945                           1.538462           0.931174

      Errors_Leading_To_Shot_Per_90
0                          0.000000
2                          0.000000
3                          0.029155
4                          0.000000
5                          0.000000
...                             ...
1939                       0.098039
1940                       0.000000
1942                       0.000000
1943                       0.156250
1945                       0.000000

[1794 rows x 41 columns]

In [15]:
main_dataset.head(50)

,Rank,Player,Nationality,Position,Age,Birth_Year,Matches_Played,Games_Started,Minutes,90s_Played,...,Dribblers_Tackled_Per_90,Dribbles_Challenged_Per_90,Challenges_Lost_Per_90,Blocks_Per_90,Shots_Blocked_Per_90,Passes_Blocked_Per_90,Interceptions_Per_90,Tackles_Plus_Interceptions_Per_90,Clearances_Per_90,Errors_Leading_To_Shot_Per_90
0,625,Aaron Cresswell,eng ENG,DF,34.0,1989.0,18,10,824,9.2,...,0.978261,1.195652,0.217391,0.978261,0.434783,0.543478,0.869565,2.065217,4.021739,0.000000
2,2744,Aaron Wan-Bissaka,cd COD,DF,26.0,1997.0,36,35,3154,35.0,...,0.657143,0.914286,0.257143,1.057143,0.314286,0.742857,1.885714,3.885714,3.571429,0.000000
3,1638,Aarón Martín,es ESP,DF,27.0,1997.0,36,35,3085,34.3,...,0.962099,1.486880,0.524781,0.962099,0.320700,0.641399,0.553936,2.623907,2.128280,0.029155
4,2534,Abakar Sylla,ci CIV,DF,21.0,2002.0,21,10,950,10.6,...,1.415094,1.603774,0.188679,1.698113,0.943396,0.754717,1.037736,3.584906,5.943396,0.000000
5,2423,Abdallah Sima,sn SEN,"FW,MF",23.0,2001.0,27,14,1238,13.8,...,0.289855,0.797101,0.507246,0.652174,0.072464,0.579710,0.072464,1.159420,0.652174,0.000000
6,865,Abde Ezzalzouli,ma MAR,"FW,MF",22.0,2001.0,32,23,1984,22.0,...,0.681818,1.227273,0.545455,1.000000,0.136364,0.863636,0.318182,2.000000,0.863636,0.000000
7,16,Abdel Abqar,ma MAR,DF,25.0,1999.0,29,29,2463,27.4,...,0.729927,1.240876,0.510949,1.021898,0.656934,0.364964,1.423358,2.737226,5.328467,0.036496
8,1129,Abdou Harroui,nl NED,"MF,FW",26.0,1998.0,10,5,463,5.1,...,0.784314,0.784314,0.000000,0.980392,0.000000,0.980392,0.392157,2.156863,0.980392,0.000000
9,2004,Abdoul Ouattara,fr FRA,"DF,FW",18.0,2005.0,17,3,471,5.2,...,0.576923,0.961538,0.384615,1.923077,0.000000,1.923077,1.730769,2.884615,2.307692,0.384615
10,222,Abdoulaye Bamba,ci CIV,DF,34.0,1990.0,19,16,1510,16.8,...,0.833333,1.130952,0.297619,0.833333,0.476190,0.357143,1.130952,2.440476,4.702381,0.000000
11,771,Abdoulaye Doucouré,ml MLI,MF,31.0,1993.0,33,31,2564,28.5,...,0.491228,1.508772,1.017544,1.087719,0.210526,0.877193,0.350877,2.035088,0.701754,0.035088
12,1895,Abdoulaye Niakhate Ndiaye,sn SEN,DF,22.0,2002.0,22,19,1707,19.0,...,1.315789,1.947368,0.631579,1.526316,0.894737,0.631579,0.578947,3.157895,7.578947,0.157895
13,2617,Abdoulaye Touré,gn GUI,MF,30.0,1994.0,28,26,2324,25.8,...,1.279070,2.286822,1.007752,1.395349,0.736434,0.658915,1.317829,3.682171,1.627907,0.193798
14,1353,Abdukodir Khusanov,uz UZB,DF,20.0,2004.0,13,11,975,10.8,...,0.648148,1.018519,0.370370,1.574074,1.018519,0.555556,2.407407,3.796296,5.277778,0.000000
15,875,Abdul Fatawu Issahaku,gh GHA,FW,20.0,2004.0,11,6,579,6.4,...,1.718750,2.968750,1.250000,1.093750,0.000000,1.093750,0.625000,3.906250,1.875000,0.000000
16,1818,Abdul Mumin,gh GHA,DF,26.0,1998.0,24,24,2017,22.4,...,0.758929,1.205357,0.446429,1.785714,1.294643,0.491071,1.026786,2.678571,5.580357,0.000000
17,1285,Abdulai Juma Bah,sl SLE,DF,18.0,2006.0,12,10,864,9.6,...,0.312500,0.520833,0.208333,1.562500,0.833333,0.729167,1.250000,2.291667,6.250000,0.000000
18,2150,Abdón Prats,es ESP,"FW,MF",31.0,1992.0,24,3,456,5.1,...,0.196078,0.392157,0.196078,0.392157,0.196078,0.196078,0.196078,0.588235,0.980392,0.000000
19,391,Abel Bretones,es ESP,DF,23.0,2000.0,35,20,2074,23.0,...,1.695652,2.739130,1.043478,1.260870,0.173913,1.086957,0.782609,3.434783,2.782609,0.086957
20,2274,Abel Ruiz,es ESP,FW,24.0,2000.0,23,17,1346,15.0,...,0.133333,0.333333,0.200000,0.466667,0.133333,0.333333,0.333333,0.733333,0.466667,0.000000
21,14,Abner,br BRA,DF,24.0,2000.0,19,12,1090,12.1,...,1.735537,2.644628,0.909091,1.239669,0.165289,1.074380,0.413223,2.809917,3.388430,0.000000
22,1118,Achraf Hakimi,ma MAR,DF,25.0,1998.0,25,24,2066,23.0,...,1.173913,2.391304,1.217391,1.086957,0.086957,1.000000,1.347826,3.434783,0.782609,0.130435
23,152,Adam Armstrong,eng ENG,"FW,MF",27.0,1997.0,20,15,1248,13.9,...,0.215827,1.007194,0.791367,0.431655,0.071942,0.359712,0.215827,1.079137,0.575540,0.000000
24,188,Adam Aznou,ma MAR,DF,18.0,2006.0,13,10,876,9.7,...,2.164948,4.432990,2.268041,2.474227,0.824742,1.649485,1.030928,3.917526,3.092784,0.000000
25,1166,Adam Hložek,cz CZE,"FW,MF",22.0,2002.0,27,22,1871,20.8,...,0.528846,0.961538,0.432692,0.625000,0.048077,0.576923,0.192308,1.250000,0.961538,0.000000
26,1659,Adam Marušić,me MNE,DF,31.0,1992.0,35,26,2337,26.0,...,0.692308,1.153846,0.461538,0.692308,0.307692,0.384615,0.615385,1.846154,2.346154,0.000000
27,1662,Adam Masina,ma MAR,DF,30.0,1994.0,28,20,1919,21.3,...,1.079812,1.877934,0.798122,1.314554,0.704225,0.610329,1.267606,2.816901,4.460094,0.093897
28,1938,Adam Obert,sk SVK,DF,21.0,2002.0,21,13,1077,12.0,...,1.333333,2.250000,0.916667,1.583333,0.583333,1.000000,1.916667,4.500000,4.000000,0.166667
29,2455,Adam Smith,eng ENG,DF,33.0,1991.0,25,19,1590,17.7,...,0.790960,1.525424,0.734463,0.734463,0.282486,0.451977,0.847458,2.203390,2.768362,0.056497
30,2753,Adam Webster,eng ENG,DF,29.0,1995.0,14,11,887,9.9,...,0.606061,1.414141,0.808081,1.616162,0.909091,0.707071,2.020202,3.030303,4.141414,0.202020
31,2763,Adam Wharton,eng ENG,MF,20.0,2004.0,20,16,1318,14.6,...,1.164384,3.013699,1.849315,0.753425,0.136986,0.616438,1.369863,3.698630,1.849315,0.000000
32,353,Adama Boiro,es ESP,"DF,FW",22.0,2002.0,18,13,1101,12.2,...,0.819672,1.229508,0.409836,0.819672,0.245902,0.573770,0.983607,2.622951,2.213115,0.081967
33,2624,Adama Traoré,es ESP,"FW,MF",28.0,1996.0,36,18,1772,19.7,...,0.253807,0.659898,0.406091,0.355330,0.000000,0.355330,0.050761,1.065990,0.304569,0.203046
34,1515,Ademola Lookman,ng NGA,"MF,FW",26.0,1997.0,31,28,2247,25.0,...,0.440000,0.760000,0.320000,0.760000,0.000000,0.760000,0.120000,1.400000,0.200000,0.040000
35,1242,Adnan Januzaj,be BEL,"MF,FW",29.0,1995.0,18,5,598,6.6,...,0.757576,1.363636,0.606061,0.909091,0.000000,0.909091,0.303030,1.818182,0.454545,0.000000
36,1972,Ado Onaiwu,jp JPN,"MF,FW",28.0,1995.0,31,9,957,10.6,...,0.377358,1.320755,0.943396,1.132075,0.000000,1.132075,0.283019,1.320755,1.132075,0.000000
37,836,Adri Embarba,es ESP,"FW,MF",32.0,1992.0,35,18,1607,17.9,...,1.005587,2.625698,1.620112,1.005587,0.055866,0.949721,0.726257,3.016760,0.782123,0.111732
38,266,Adrian Beck,de GER,"MF,FW",27.0,1997.0,32,18,1598,17.8,...,0.674157,1.966292,1.292135,1.741573,0.112360,1.629213,0.505618,2.528090,0.955056,0.000000
39,311,Adrian Bernabe,es ESP,MF,23.0,2001.0,21,18,1453,16.1,...,0.869565,1.987578,1.118012,1.366460,0.559006,0.807453,0.434783,2.236025,1.614907,0.062112
40,2162,Adrien Rabiot,fr FRA,MF,29.0,1995.0,29,27,2485,27.6,...,0.688406,1.159420,0.471014,0.760870,0.072464,0.688406,0.760870,2.536232,1.159420,0.000000
41,2546,Adrien Tameze,cm CMR,"MF,DF",30.0,1994.0,20,9,649,7.2,...,0.138889,1.388889,1.250000,1.111111,0.694444,0.416667,1.388889,2.083333,1.111111,0.138889
42,2590,Adrien Thomasson,fr FRA,MF,30.0,1993.0,33,31,2615,29.1,...,1.786942,3.264605,1.477663,1.649485,0.103093,1.546392,0.652921,3.745704,0.962199,0.068729
43,2636,Adrien Truffert,fr FRA,"DF,MF",22.0,2001.0,33,31,2752,30.6,...,1.045752,1.568627,0.522876,1.437908,0.196078,1.241830,0.882353,2.875817,1.830065,0.032680
44,98,Adrià Altimira,es ESP,"DF,FW",23.0,2001.0,22,19,1630,18.1,...,1.325967,2.209945,0.883978,0.828729,0.331492,0.497238,0.828729,3.093923,2.983425,0.110497
45,2065,Adrià Pedrosa,es ESP,DF,26.0,1998.0,31,27,2298,25.5,...,1.215686,2.117647,0.901961,1.686275,0.431373,1.254902,0.941176,3.137255,3.333333,0.000000
47,1822,Aihen Muñoz,es ESP,DF,26.0,1997.0,21,13,1098,12.2,...,1.147541,2.295082,1.147541,0.901639,0.491803,0.409836,1.147541,3.114754,3.852459,0.000000
48,1992,Aimar Oroz,es ESP,MF,22.0,2001.0,37,35,2966,33.0,...,0.424242,1.393939,0.969697,0.878788,0.060606,0.818182,0.606061,1.666667,0.303030,0.000000
49,1804,Aimen Moueffek,fr FRA,MF,23.0,2001.0,22,13,1039,11.5,...,0.869565,2.000000,1.130435,1.739130,0.608696,1.130435,0.434783,2.173913,2.260870,0.086957
50,1577,Ainsley Maitland-Niles,eng ENG,DF,26.0,1997.0,32,20,1985,22.1,...,2.171946,3.438914,1.266968,1.266968,0.180995,1.085973,1.131222,4.343891,2.760181,0.271493
51,2039,Aitor Paredes,es ESP,DF,24.0,2000.0,23,21,1812,20.1,...,0.398010,0.746269,0.348259,1.293532,0.746269,0.547264,1.094527,1.840796,5.671642,0.199005

In [16]:
print(f"combined_stats_dataset: {len(combined_stats_dataset)} regular players")

combined_stats_dataset: 1794 regular players

In [17]:
# check for NaNs
check_nans = combined_stats_dataset.isna().sum().sum()
print(check_nans)

0

In [18]:
#save as csv file
combined_stats_dataset.to_csv('combined_stats_dataset_1.csv', index=False)

In [19]:
print(combined_stats_dataset)

      Rank                 Player Nationality Position   Age  Birth_Year  \
0      625        Aaron Cresswell     eng ENG       DF  34.0      1989.0
2     2744      Aaron Wan-Bissaka      cd COD       DF  26.0      1997.0
3     1638           Aarón Martín      es ESP       DF  27.0      1997.0
4     2534           Abakar Sylla      ci CIV       DF  21.0      2002.0
5     2423          Abdallah Sima      sn SEN    FW,MF  23.0      2001.0
...    ...                    ...         ...      ...   ...         ...
1939  2660         Óscar Valentín      es ESP       MF  29.0      1994.0
1940  1618        Óscar de Marcos      es ESP       DF  35.0      1989.0
1942    62             Ümit Akdag      ro ROU       DF  20.0      2003.0
1943  1265  Þórir Jóhann Helgason      is ISL       MF  23.0      2000.0
1945  1098         İlkay Gündoğan      de GER       MF  33.0      1990.0

      Matches_Played  Games_Started  Minutes  90s_Played  ...  \
0                 18             10      824         9.2  ...
2                 36             35     3154        35.0  ...
3                 36             35     3085        34.3  ...
4                 21             10      950        10.6  ...
5                 27             14     1238        13.8  ...
...              ...            ...      ...         ...  ...
1939              34             18     1835        20.4  ...
1940              26             17     1564        17.4  ...
1942               9              6      500         5.6  ...
1943              21             13     1156        12.8  ...
1945              33             25     2223        24.7  ...

      Dribblers_Tackled_Per_90  Dribbles_Challenged_Per_90  \
0                     0.978261                    1.195652
2                     0.657143                    0.914286
3                     0.962099                    1.486880
4                     1.415094                    1.603774
5                     0.289855                    0.797101
...                        ...                         ...
1939                  1.617647                    3.725490
1940                  1.206897                    2.126437
1942                  0.892857                    2.142857
1943                  0.546875                    1.015625
1945                  0.404858                    0.971660

      Challenges_Lost_Per_90  Blocks_Per_90  Shots_Blocked_Per_90  \
0                   0.217391       0.978261              0.434783
2                   0.257143       1.057143              0.314286
3                   0.524781       0.962099              0.320700
4                   0.188679       1.698113              0.943396
5                   0.507246       0.652174              0.072464
...                      ...            ...                   ...
1939                2.107843       1.764706              0.392157
1940                0.919540       0.977011              0.057471
1942                1.250000       1.785714              1.428571
1943                0.468750       0.546875              0.156250
1945                0.566802       0.607287              0.000000

      Passes_Blocked_Per_90  Interceptions_Per_90  \
0                  0.543478              0.869565
2                  0.742857              1.885714
3                  0.641399              0.553936
4                  0.754717              1.037736
5                  0.579710              0.072464
...                     ...                   ...
1939               1.372549              1.029412
1940               0.919540              0.919540
1942               0.357143              1.964286
1943               0.390625              0.468750
1945               0.607287              0.526316

      Tackles_Plus_Interceptions_Per_90  Clearances_Per_90  \
0                              2.065217           4.021739
2                              3.885714           3.571429
3                              2.623907           2.128280
4                              3.584906           5.943396
5                              1.159420           0.652174
...                                 ...                ...
1939                           3.725490           2.500000
1940                           2.758621           2.011494
1942                           3.392857           3.392857
1943                           1.250000           0.859375
1945                           1.538462           0.931174

      Errors_Leading_To_Shot_Per_90
0                          0.000000
2                          0.000000
3                          0.029155
4                          0.000000
5                          0.000000
...                             ...
1939                       0.098039
1940                       0.000000
1942                       0.000000
1943                       0.156250
1945                       0.000000

[1794 rows x 41 columns]

In [20]:
print(combined_stats_dataset.head(50))

    Rank                     Player Nationality Position   Age  Birth_Year  \
0    625            Aaron Cresswell     eng ENG       DF  34.0      1989.0
2   2744          Aaron Wan-Bissaka      cd COD       DF  26.0      1997.0
3   1638               Aarón Martín      es ESP       DF  27.0      1997.0
4   2534               Abakar Sylla      ci CIV       DF  21.0      2002.0
5   2423              Abdallah Sima      sn SEN    FW,MF  23.0      2001.0
6    865            Abde Ezzalzouli      ma MAR    FW,MF  22.0      2001.0
7     16                Abdel Abqar      ma MAR       DF  25.0      1999.0
8   1129              Abdou Harroui      nl NED    MF,FW  26.0      1998.0
9   2004            Abdoul Ouattara      fr FRA    DF,FW  18.0      2005.0
10   222            Abdoulaye Bamba      ci CIV       DF  34.0      1990.0
11   771         Abdoulaye Doucouré      ml MLI       MF  31.0      1993.0
12  1895  Abdoulaye Niakhate Ndiaye      sn SEN       DF  22.0      2002.0
13  2617            Abdoulaye Touré      gn GUI       MF  30.0      1994.0
14  1353         Abdukodir Khusanov      uz UZB       DF  20.0      2004.0
15   875      Abdul Fatawu Issahaku      gh GHA       FW  20.0      2004.0
16  1818                Abdul Mumin      gh GHA       DF  26.0      1998.0
17  1285           Abdulai Juma Bah      sl SLE       DF  18.0      2006.0
18  2150                Abdón Prats      es ESP    FW,MF  31.0      1992.0
19   391              Abel Bretones      es ESP       DF  23.0      2000.0
20  2274                  Abel Ruiz      es ESP       FW  24.0      2000.0
21    14                      Abner      br BRA       DF  24.0      2000.0
22  1118              Achraf Hakimi      ma MAR       DF  25.0      1998.0
23   152             Adam Armstrong     eng ENG    FW,MF  27.0      1997.0
24   188                 Adam Aznou      ma MAR       DF  18.0      2006.0
25  1166                Adam Hložek      cz CZE    FW,MF  22.0      2002.0
26  1659               Adam Marušić      me MNE       DF  31.0      1992.0
27  1662                Adam Masina      ma MAR       DF  30.0      1994.0
28  1938                 Adam Obert      sk SVK       DF  21.0      2002.0
29  2455                 Adam Smith     eng ENG       DF  33.0      1991.0
30  2753               Adam Webster     eng ENG       DF  29.0      1995.0
31  2763               Adam Wharton     eng ENG       MF  20.0      2004.0
32   353                Adama Boiro      es ESP    DF,FW  22.0      2002.0
33  2624               Adama Traoré      es ESP    FW,MF  28.0      1996.0
34  1515            Ademola Lookman      ng NGA    MF,FW  26.0      1997.0
35  1242              Adnan Januzaj      be BEL    MF,FW  29.0      1995.0
36  1972                 Ado Onaiwu      jp JPN    MF,FW  28.0      1995.0
37   836               Adri Embarba      es ESP    FW,MF  32.0      1992.0
38   266                Adrian Beck      de GER    MF,FW  27.0      1997.0
39   311             Adrian Bernabe      es ESP       MF  23.0      2001.0
40  2162              Adrien Rabiot      fr FRA       MF  29.0      1995.0
41  2546              Adrien Tameze      cm CMR    MF,DF  30.0      1994.0
42  2590           Adrien Thomasson      fr FRA       MF  30.0      1993.0
43  2636            Adrien Truffert      fr FRA    DF,MF  22.0      2001.0
44    98             Adrià Altimira      es ESP    DF,FW  23.0      2001.0
45  2065              Adrià Pedrosa      es ESP       DF  26.0      1998.0
47  1822                Aihen Muñoz      es ESP       DF  26.0      1997.0
48  1992                 Aimar Oroz      es ESP       MF  22.0      2001.0
49  1804             Aimen Moueffek      fr FRA       MF  23.0      2001.0
50  1577     Ainsley Maitland-Niles     eng ENG       DF  26.0      1997.0
51  2039              Aitor Paredes      es ESP       DF  24.0      2000.0

    Matches_Played  Games_Started  Minutes  90s_Played  ...  \
0               18             10      824         9.2  ...
2               36             35     3154        35.0  ...
3               36             35     3085        34.3  ...
4               21             10      950        10.6  ...
5               27             14     1238        13.8  ...
6               32             23     1984        22.0  ...
7               29             29     2463        27.4  ...
8               10              5      463         5.1  ...
9               17              3      471         5.2  ...
10              19             16     1510        16.8  ...
11              33             31     2564        28.5  ...
12              22             19     1707        19.0  ...
13              28             26     2324        25.8  ...
14              13             11      975        10.8  ...
15              11              6      579         6.4  ...
16              24             24     2017        22.4  ...
17              12             10      864         9.6  ...
18              24              3      456         5.1  ...
19              35             20     2074        23.0  ...
20              23             17     1346        15.0  ...
21              19             12     1090        12.1  ...
22              25             24     2066        23.0  ...
23              20             15     1248        13.9  ...
24              13             10      876         9.7  ...
25              27             22     1871        20.8  ...
26              35             26     2337        26.0  ...
27              28             20     1919        21.3  ...
28              21             13     1077        12.0  ...
29              25             19     1590        17.7  ...
30              14             11      887         9.9  ...
31              20             16     1318        14.6  ...
32              18             13     1101        12.2  ...
33              36             18     1772        19.7  ...
34              31             28     2247        25.0  ...
35              18              5      598         6.6  ...
36              31              9      957        10.6  ...
37              35             18     1607        17.9  ...
38              32             18     1598        17.8  ...
39              21             18     1453        16.1  ...
40              29             27     2485        27.6  ...
41              20              9      649         7.2  ...
42              33             31     2615        29.1  ...
43              33             31     2752        30.6  ...
44              22             19     1630        18.1  ...
45              31             27     2298        25.5  ...
47              21             13     1098        12.2  ...
48              37             35     2966        33.0  ...
49              22             13     1039        11.5  ...
50              32             20     1985        22.1  ...
51              23             21     1812        20.1  ...

    Dribblers_Tackled_Per_90  Dribbles_Challenged_Per_90  \
0                   0.978261                    1.195652
2                   0.657143                    0.914286
3                   0.962099                    1.486880
4                   1.415094                    1.603774
5                   0.289855                    0.797101
6                   0.681818                    1.227273
7                   0.729927                    1.240876
8                   0.784314                    0.784314
9                   0.576923                    0.961538
10                  0.833333                    1.130952
11                  0.491228                    1.508772
12                  1.315789                    1.947368
13                  1.279070                    2.286822
14                  0.648148                    1.018519
15                  1.718750                    2.968750
16                  0.758929                    1.205357
17                  0.312500                    0.520833
18                  0.196078                    0.392157
19                  1.695652                    2.739130
20                  0.133333                    0.333333
21                  1.735537                    2.644628
22                  1.173913                    2.391304
23                  0.215827                    1.007194
24                  2.164948                    4.432990
25                  0.528846                    0.961538
26                  0.692308                    1.153846
27                  1.079812                    1.877934
28                  1.333333                    2.250000
29                  0.790960                    1.525424
30                  0.606061                    1.414141
31                  1.164384                    3.013699
32                  0.819672                    1.229508
33                  0.253807                    0.659898
34                  0.440000                    0.760000
35                  0.757576                    1.363636
36                  0.377358                    1.320755
37                  1.005587                    2.625698
38                  0.674157                    1.966292
39                  0.869565                    1.987578
40                  0.688406                    1.159420
41                  0.138889                    1.388889
42                  1.786942                    3.264605
43                  1.045752                    1.568627
44                  1.325967                    2.209945
45                  1.215686                    2.117647
47                  1.147541                    2.295082
48                  0.424242                    1.393939
49                  0.869565                    2.000000
50                  2.171946                    3.438914
51                  0.398010                    0.746269

    Challenges_Lost_Per_90  Blocks_Per_90  Shots_Blocked_Per_90  \
0                 0.217391       0.978261              0.434783
2                 0.257143       1.057143              0.314286
3                 0.524781       0.962099              0.320700
4                 0.188679       1.698113              0.943396
5                 0.507246       0.652174              0.072464
6                 0.545455       1.000000              0.136364
7                 0.510949       1.021898              0.656934
8                 0.000000       0.980392              0.000000
9                 0.384615       1.923077              0.000000
10                0.297619       0.833333              0.476190
11                1.017544       1.087719              0.210526
12                0.631579       1.526316              0.894737
13                1.007752       1.395349              0.736434
14                0.370370       1.574074              1.018519
15                1.250000       1.093750              0.000000
16                0.446429       1.785714              1.294643
17                0.208333       1.562500              0.833333
18                0.196078       0.392157              0.196078
19                1.043478       1.260870              0.173913
20                0.200000       0.466667              0.133333
21                0.909091       1.239669              0.165289
22                1.217391       1.086957              0.086957
23                0.791367       0.431655              0.071942
24                2.268041       2.474227              0.824742
25                0.432692       0.625000              0.048077
26                0.461538       0.692308              0.307692
27                0.798122       1.314554              0.704225
28                0.916667       1.583333              0.583333
29                0.734463       0.734463              0.282486
30                0.808081       1.616162              0.909091
31                1.849315       0.753425              0.136986
32                0.409836       0.819672              0.245902
33                0.406091       0.355330              0.000000
34                0.320000       0.760000              0.000000
35                0.606061       0.909091              0.000000
36                0.943396       1.132075              0.000000
37                1.620112       1.005587              0.055866
38                1.292135       1.741573              0.112360
39                1.118012       1.366460              0.559006
40                0.471014       0.760870              0.072464
41                1.250000       1.111111              0.694444
42                1.477663       1.649485              0.103093
43                0.522876       1.437908              0.196078
44                0.883978       0.828729              0.331492
45                0.901961       1.686275              0.431373
47                1.147541       0.901639              0.491803
48                0.969697       0.878788              0.060606
49                1.130435       1.739130              0.608696
50                1.266968       1.266968              0.180995
51                0.348259       1.293532              0.746269

    Passes_Blocked_Per_90  Interceptions_Per_90  \
0                0.543478              0.869565
2                0.742857              1.885714
3                0.641399              0.553936
4                0.754717              1.037736
5                0.579710              0.072464
6                0.863636              0.318182
7                0.364964              1.423358
8                0.980392              0.392157
9                1.923077              1.730769
10               0.357143              1.130952
11               0.877193              0.350877
12               0.631579              0.578947
13               0.658915              1.317829
14               0.555556              2.407407
15               1.093750              0.625000
16               0.491071              1.026786
17               0.729167              1.250000
18               0.196078              0.196078
19               1.086957              0.782609
20               0.333333              0.333333
21               1.074380              0.413223
22               1.000000              1.347826
23               0.359712              0.215827
24               1.649485              1.030928
25               0.576923              0.192308
26               0.384615              0.615385
27               0.610329              1.267606
28               1.000000              1.916667
29               0.451977              0.847458
30               0.707071              2.020202
31               0.616438              1.369863
32               0.573770              0.983607
33               0.355330              0.050761
34               0.760000              0.120000
35               0.909091              0.303030
36               1.132075              0.283019
37               0.949721              0.726257
38               1.629213              0.505618
39               0.807453              0.434783
40               0.688406              0.760870
41               0.416667              1.388889
42               1.546392              0.652921
43               1.241830              0.882353
44               0.497238              0.828729
45               1.254902              0.941176
47               0.409836              1.147541
48               0.818182              0.606061
49               1.130435              0.434783
50               1.085973              1.131222
51               0.547264              1.094527

    Tackles_Plus_Interceptions_Per_90  Clearances_Per_90  \
0                            2.065217           4.021739
2                            3.885714           3.571429
3                            2.623907           2.128280
4                            3.584906           5.943396
5                            1.159420           0.652174
6                            2.000000           0.863636
7                            2.737226           5.328467
8                            2.156863           0.980392
9                            2.884615           2.307692
10                           2.440476           4.702381
11                           2.035088           0.701754
12                           3.157895           7.578947
13                           3.682171           1.627907
14                           3.796296           5.277778
15                           3.906250           1.875000
16                           2.678571           5.580357
17                           2.291667           6.250000
18                           0.588235           0.980392
19                           3.434783           2.782609
20                           0.733333           0.466667
21                           2.809917           3.388430
22                           3.434783           0.782609
23                           1.079137           0.575540
24                           3.917526           3.092784
25                           1.250000           0.961538
26                           1.846154           2.346154
27                           2.816901           4.460094
28                           4.500000           4.000000
29                           2.203390           2.768362
30                           3.030303           4.141414
31                           3.698630           1.849315
32                           2.622951           2.213115
33                           1.065990           0.304569
34                           1.400000           0.200000
35                           1.818182           0.454545
36                           1.320755           1.132075
37                           3.016760           0.782123
38                           2.528090           0.955056
39                           2.236025           1.614907
40                           2.536232           1.159420
41                           2.083333           1.111111
42                           3.745704           0.962199
43                           2.875817           1.830065
44                           3.093923           2.983425
45                           3.137255           3.333333
47                           3.114754           3.852459
48                           1.666667           0.303030
49                           2.173913           2.260870
50                           4.343891           2.760181
51                           1.840796           5.671642

    Errors_Leading_To_Shot_Per_90
0                        0.000000
2                        0.000000
3                        0.029155
4                        0.000000
5                        0.000000
6                        0.000000
7                        0.036496
8                        0.000000
9                        0.384615
10                       0.000000
11                       0.035088
12                       0.157895
13                       0.193798
14                       0.000000
15                       0.000000
16                       0.000000
17                       0.000000
18                       0.000000
19                       0.086957
20                       0.000000
21                       0.000000
22                       0.130435
23                       0.000000
24                       0.000000
25                       0.000000
26                       0.000000
27                       0.093897
28                       0.166667
29                       0.056497
30                       0.202020
31                       0.000000
32                       0.081967
33                       0.203046
34                       0.040000
35                       0.000000
36                       0.000000
37                       0.111732
38                       0.000000
39                       0.062112
40                       0.000000
41                       0.138889
42                       0.068729
43                       0.032680
44                       0.110497
45                       0.000000